github: cl2raul66          # GitHub Sponsors (tu usuario)
patreon: username           # Patreon
open_collective: username   # Open Collective
ko_fi: username             # Ko-fi
tidelift: name              # Tidelift
community_bridge: project   # Community Bridge
liberapay: username         # Liberapay
issuehunt: username         # IssueHunt
otechie: username           # Otechie
lfx_crowdfunding: project   # Linux Foundation
custom: [url1, url2]        # Links personalizados
