<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>

		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>EasyWindowsApplication</Title>
		<Copyright>MIT License</Copyright>
		<PackageProjectUrl>https://github.com/cl2raul66/EasyWindowsApplication/src/EasyWindowsApplication</PackageProjectUrl>
		<RepositoryUrl>https://github.com/cl2raul66/EasyWindowsApplication</RepositoryUrl>
		<PackageTags>csharp-library; win32; windows-application;</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<Version>0.0.0</Version>
		<Authors>cl2raul66</Authors>
		<Company>RandAMediaLabGroup</Company>
		<PackageId>RandAMediaLabGroup.EasyWindowsApplication</PackageId>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>logo_template.png</PackageIcon>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<IsAotCompatible>True</IsAotCompatible>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<IsAotCompatible>True</IsAotCompatible>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\rsc\Images\logo_template.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Common\" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="EasyWindowsApplication.Generators" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Svg.Skia" Version="*" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EasyWindowsApplication.Generators\EasyWindowsApplication.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

</Project>
