using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EasyWindowsApplication.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class ControlActivatorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, (spc, compilation) =>
        {
            // Solo generar en el assembly que define ControlActivatorRegistry (EasyWindowsApplication)
            var registryType = compilation.Assembly.GetTypeByMetadataName("EasyWindowsApplication.Common.ControlActivatorRegistry");
            if (registryType is null) return;

            var activatorInterface = compilation.GetTypeByMetadataName("EasyWindowsApplication.Common.IControlActivator");
            if (activatorInterface is null) return;

            var candidates = new List<INamedTypeSymbol>();

            // Recorre tipos del assembly principal (EasyWindowsApplication) — incluye Win32ControlActivator y futuros plugins en mismo ensamblado
            CollectTypes(compilation.Assembly.GlobalNamespace, activatorInterface, candidates);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#pragma warning disable CS0612, CS0618, CS1591, CA2255");
            sb.AppendLine("using EasyWindowsApplication.Common;");
            sb.AppendLine();
            sb.AppendLine("namespace EasyWindowsApplication.Common;");
            sb.AppendLine();
            sb.AppendLine("internal sealed partial class ControlActivatorRegistry");
            sb.AppendLine("{");
            sb.AppendLine("    static partial void RegisterGeneratedActivators()");
            sb.AppendLine("    {");

            // Fallback hardcode para Win32ControlsModule (garantiza registro incluso si escaneo falla)
            var hasWin32 = candidates.Any(c => c.Name == "Win32ControlActivator");
            if (!hasWin32)
            {
                // Verificación por nombre si el escaneo por AllInterfaces falló por InternalsVisibleTo timing
                sb.AppendLine("        new global::EasyWindowsApplication.Win32ControlsModule.Backend.Win32ControlActivator().RegisterActivators(Shared);");
            }

            foreach (var type in candidates.Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default).OrderBy(t => t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)))
            {
                // Evitar generar la interfaz misma y evitar duplicar Win32 si ya hardcodeado
                if (SymbolEqualityComparer.Default.Equals(type, activatorInterface)) continue;
                if (type.Name == "Win32ControlActivator" && !hasWin32) continue; // ya emitido arriba
                var fqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"        new {fqn}().RegisterActivators(Shared);");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("ControlActivatorRegistrations.g.cs", sb.ToString());
        });
    }

    private static void CollectTypes(INamespaceSymbol ns, INamedTypeSymbol activatorInterface, List<INamedTypeSymbol> candidates)
    {
        foreach (var member in ns.GetMembers())
        {
            if (member is INamespaceSymbol nestedNs)
            {
                CollectTypes(nestedNs, activatorInterface, candidates);
            }
            else if (member is INamedTypeSymbol type)
            {
                CollectNestedTypes(type, activatorInterface, candidates);
            }
        }
    }

    private static void CollectNestedTypes(INamedTypeSymbol type, INamedTypeSymbol activatorInterface, List<INamedTypeSymbol> candidates)
    {
        // Incluir el tipo si implementa IControlActivator
        foreach (var iface in type.AllInterfaces)
        {
            if (SymbolEqualityComparer.Default.Equals(iface, activatorInterface))
            {
                if (!type.IsAbstract)
                    candidates.Add(type);
                break;
            }
        }

        // Recursión en tipos anidados
        foreach (var nested in type.GetTypeMembers())
        {
            CollectNestedTypes(nested, activatorInterface, candidates);
        }
    }
}
