using Microsoft.CodeAnalysis;
using System.Text;

namespace EasyWindowsApplication.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class CulturesGenerator : IIncrementalGenerator
{
    private const string LibraryAssemblyName = "EasyWindowsApplication";

    private static readonly string[,] Cultures = new[,]
    {
        { "En", "en" },
        { "EnUS", "en-US" },
        { "EnGB", "en-GB" },
        { "EnCA", "en-CA" },
        { "EnAU", "en-AU" },
        { "EnIN", "en-IN" },
        { "Es", "es" },
        { "EsES", "es-ES" },
        { "EsMX", "es-MX" },
        { "EsAR", "es-AR" },
        { "EsCO", "es-CO" },
        { "EsCL", "es-CL" },
        { "Fr", "fr" },
        { "FrFR", "fr-FR" },
        { "FrCA", "fr-CA" },
        { "De", "de" },
        { "DeDE", "de-DE" },
        { "DeAT", "de-AT" },
        { "DeCH", "de-CH" },
        { "It", "it" },
        { "ItIT", "it-IT" },
        { "ItCH", "it-CH" },
        { "Pt", "pt" },
        { "PtBR", "pt-BR" },
        { "PtPT", "pt-PT" },
        { "Nl", "nl" },
        { "NlNL", "nl-NL" },
        { "NlBE", "nl-BE" },
        { "Pl", "pl" },
        { "PlPL", "pl-PL" },
        { "Ru", "ru" },
        { "RuRU", "ru-RU" },
        { "UkUA", "uk-UA" },
        { "TrTR", "tr-TR" },
        { "SvSE", "sv-SE" },
        { "NbNO", "nb-NO" },
        { "DaDK", "da-DK" },
        { "FiFI", "fi-FI" },
        { "CsCZ", "cs-CZ" },
        { "HuHU", "hu-HU" },
        { "ElGR", "el-GR" },
        { "HeIL", "he-IL" },
        { "ThTH", "th-TH" },
        { "ViVN", "vi-VN" },
        { "IdID", "id-ID" },
        { "MsMY", "ms-MY" },
        { "RoRO", "ro-RO" },
        { "BgBG", "bg-BG" },
        { "HrHR", "hr-HR" },
        { "SkSK", "sk-SK" },
        { "CaES", "ca-ES" },
        { "Zh", "zh" },
        { "ZhCN", "zh-CN" },
        { "ZhTW", "zh-TW" },
        { "ZhHK", "zh-HK" },
        { "Ja", "ja" },
        { "JaJP", "ja-JP" },
        { "KoKR", "ko-KR" },
        { "HiIN", "hi-IN" },
        { "Ar", "ar" },
        { "ArSA", "ar-SA" },
        { "ArEG", "ar-EG" },
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.CompilationProvider.Select(static (compilation, _) =>
                compilation.AssemblyName == LibraryAssemblyName),
            static (spc, isLibrary) =>
            {
                if (isLibrary)
                {
                    var sb = new StringBuilder();
                    sb.AppendLine("// <auto-generated />");
                    sb.AppendLine("using System.Globalization;");
                    sb.AppendLine();
                    sb.AppendLine("namespace EasyWindowsApplication.Share;");
                    sb.AppendLine();
                    sb.AppendLine("public static class Cultures");
                    sb.AppendLine("{");
                    for (int i = 0; i < Cultures.GetLength(0); i++)
                    {
                        sb.AppendLine($"    public static readonly CultureInfo CultureInfo{Cultures[i, 0]} = CultureInfo.GetCultureInfo(\"{Cultures[i, 1]}\");");
                    }
                    sb.AppendLine("}");
                    spc.AddSource("Cultures.g.cs", sb.ToString());
                }

                spc.AddSource("CulturesUsings.g.cs",
                    "// <auto-generated />\nglobal using static EasyWindowsApplication.Share.Cultures;\n");
            });
    }
}
