

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EasyWindowsApplication.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class EasyBehaviorGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor DuplicateNameRule = new(
        id: "EAWIN001",
        title: "Duplicate Name",
        messageFormat: "Name '{0}' is already used. Each Name must be unique within the application.",
        category: "EasyWindowsApplication",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor UseWinApiRequiredRule = new(
        id: "EAWIN002",
        title: "UseWinApi required",
        messageFormat: "UseWinApi() is required to use Win32 controls in Layout. Add .Resources(s => s.Setting(x => x.UseWinApi())).",
        category: "EasyWindowsApplication",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var namedItems = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => IsNameCandidate(node),
            transform: static (ctx, _) => ExtractNamedInfo(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value);

        var collected = namedItems.Collect();

        var behaviorCalls = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => IsBehaviorCandidate(node),
            transform: static (ctx, _) => ExtractEnclosingType(ctx))
            .Where(static info => info is not null);

        var enclosingType = behaviorCalls.Collect();

        var useWinApi = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => IsUseWinApiCandidate(node),
            transform: static (ctx, _) => IsUseWinApiSymbol(ctx))
            .Where(static enabled => enabled)
            .Collect()
            .Select(static (items, _) => !items.IsDefaultOrEmpty);

        var controlItems = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => IsViewControlCandidate(node),
            transform: static (ctx, _) => ExtractControlLocation(ctx))
            .Where(static location => location is not null);

        var controlLocations = controlItems.Collect();

        context.RegisterSourceOutput(
            collected.Combine(enclosingType).Combine(useWinApi).Combine(controlLocations),
            static (spc, quadruple) =>
        {
            var (((items, enclosing), usesWinApi), controls) = quadruple;

            if (!usesWinApi && !controls.IsDefaultOrEmpty)
            {
                foreach (var location in controls)
                    spc.ReportDiagnostic(Diagnostic.Create(UseWinApiRequiredRule, location));
            }

            if (items.IsDefaultOrEmpty) return;

            var seen = new HashSet<string>();
            var unique = new List<NamedInfo>();
            foreach (var item in items)
            {
                if (!seen.Add(item.Name))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        DuplicateNameRule,
                        item.Location,
                        item.Name));
                    continue;
                }
                unique.Add(item);
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#pragma warning disable CS0612, CS0618, CS1591");
            sb.AppendLine();

            var ib = "global::EasyWindowsApplication.CoreModule.Frontend.IBehaviorBuilder";

            sb.AppendLine("namespace EasyWindowsApplication");
            sb.AppendLine("{");
            sb.AppendLine("    public static class EasyBehaviorExtensions");
            sb.AppendLine("    {");

            sb.AppendLine($"        extension({ib} bh)");
            sb.AppendLine("        {");

            foreach (var item in unique)
            {
                if (!usesWinApi && !item.IsWindowType) continue;
                var propName = SanitizeName(item.Name);
                if (item.IsWindowType)
                {
                    sb.AppendLine($"            public {item.TypeSymbol} {propName}");
                    sb.AppendLine($"                => global::EasyWindowsApplication.Share.Infrastructure.ControlAccess");
                    sb.AppendLine($"                    .GetWindow<{item.TypeSymbol}>(\"{item.Name}\");");
                }
                else
                {
                    sb.AppendLine($"            public {item.TypeSymbol} {propName}");
                    sb.AppendLine($"                => global::EasyWindowsApplication.Share.Infrastructure.ControlAccess");
                    sb.AppendLine($"                    .Get<{item.TypeSymbol}>(\"{item.Name}\");");
                }
                sb.AppendLine();
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            if (!enclosing.IsDefaultOrEmpty && enclosing[0] is not null)
            {
                var enclosingInfo = enclosing[0]!;
                var ns = enclosingInfo.Namespace;
                var className = enclosingInfo.ClassName;

                if (!string.IsNullOrEmpty(ns))
                {
                    sb.AppendLine();
                    sb.AppendLine($"namespace {ns}");
                    sb.AppendLine("{");
                }

                sb.AppendLine();
                sb.AppendLine($"    partial class {className}");
                sb.AppendLine("    {");

                foreach (var item in unique)
                {
                    if (!usesWinApi && !item.IsWindowType) continue;
                    var propName = SanitizeName(item.Name);
                    if (item.IsWindowType)
                    {
                        sb.AppendLine($"        internal static {item.TypeSymbol} {propName}");
                        sb.AppendLine($"            => global::EasyWindowsApplication.Share.Infrastructure.ControlAccess");
                        sb.AppendLine($"                .GetWindow<{item.TypeSymbol}>(\"{item.Name}\");");
                    }
                    else
                    {
                        sb.AppendLine($"        internal static {item.TypeSymbol} {propName}");
                        sb.AppendLine($"            => global::EasyWindowsApplication.Share.Infrastructure.ControlAccess");
                        sb.AppendLine($"                .Get<{item.TypeSymbol}>(\"{item.Name}\");");
                    }
                    sb.AppendLine();
                }

                sb.AppendLine("    }");

                if (!string.IsNullOrEmpty(ns))
                {
                    sb.AppendLine("}");
                }
            }

            spc.AddSource("EasyBehaviorExtensions.g.cs", sb.ToString());
        });
    }

    private static bool IsNameCandidate(SyntaxNode node)
    {
        if (node is not InvocationExpressionSyntax inv)
            return false;
        if (inv.Expression is not MemberAccessExpressionSyntax ma)
            return false;
        if (ma.Name.Identifier.Text != "Name")
            return false;
        if (inv.ArgumentList.Arguments.Count != 1)
            return false;
        if (inv.ArgumentList.Arguments[0].Expression is not LiteralExpressionSyntax lit)
            return false;
        if (!lit.IsKind(SyntaxKind.StringLiteralExpression))
            return false;
        return true;
    }

    private static NamedInfo? ExtractNamedInfo(GeneratorSyntaxContext context)
    {
        var inv = (InvocationExpressionSyntax)context.Node;
        if (inv.ArgumentList.Arguments[0].Expression is not LiteralExpressionSyntax lit)
            return null;

        var name = lit.Token.ValueText;
        if (string.IsNullOrEmpty(name))
            return null;

        var location = inv.GetLocation();

        var current = inv.Parent;
        while (current is not null && current is not LambdaExpressionSyntax)
            current = current.Parent;

        if (current is not LambdaExpressionSyntax lambda)
            return null;

        if (lambda.Parent is not ArgumentSyntax argSyntax
            || argSyntax.Parent is not ArgumentListSyntax argList
            || argList.Parent is not InvocationExpressionSyntax parentInv
            || parentInv.Expression is not MemberAccessExpressionSyntax parentMa)
            return null;

        if (parentMa.Name is GenericNameSyntax generic
            && generic.Identifier.Text == "View"
            && generic.TypeArgumentList.Arguments.Count == 1)
        {
            var typeArg = generic.TypeArgumentList.Arguments[0];
            var typeSymbol = context.SemanticModel.GetTypeInfo(typeArg).Type;
            if (typeSymbol == null) return null;

            return new NamedInfo(
                name,
                typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                isWindowType: false,
                location);
        }

        if (parentMa.Name.Identifier.Text == "Window")
        {
            return new NamedInfo(name, "global::EasyWindowsApplication.WindowingModule.Frontend.IWindow", isWindowType: true, location);
        }

        if (parentMa.Name.Identifier.Text == "AlternativeWindow")
        {
            return new NamedInfo(name, "global::EasyWindowsApplication.WindowingModule.Frontend.IAlternativeWindow", isWindowType: true, location);
        }

        return null;
    }

    private static bool IsBehaviorCandidate(SyntaxNode node)
    {
        if (node is not InvocationExpressionSyntax inv)
            return false;
        if (inv.Expression is not MemberAccessExpressionSyntax memberAccess)
            return false;
        if (memberAccess.Name.Identifier.Text != "Behavior")
            return false;
        if (inv.ArgumentList.Arguments.Count != 1)
            return false;
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax)
            return false;
        return true;
    }

    private static bool IsUseWinApiCandidate(SyntaxNode node)
    {
        if (node is not InvocationExpressionSyntax inv)
            return false;
        if (inv.Expression is not MemberAccessExpressionSyntax ma)
            return false;
        if (ma.Name.Identifier.Text != "UseWinApi")
            return false;
        if (inv.ArgumentList.Arguments.Count != 0)
            return false;
        return true;
    }

    private static bool IsUseWinApiSymbol(GeneratorSyntaxContext context)
    {
        var inv = (InvocationExpressionSyntax)context.Node;
        if (inv.Expression is not MemberAccessExpressionSyntax ma)
            return false;
        var symbol = context.SemanticModel.GetSymbolInfo(ma).Symbol;
        return symbol is IMethodSymbol method
            && method.Name == "UseWinApi"
            && method.ContainingType is { } containingType
            && containingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                == "global::EasyWindowsApplication.CoreModule.Frontend.ISettingsBuilder";
    }

    private static bool IsViewControlCandidate(SyntaxNode node)
    {
        if (node is not InvocationExpressionSyntax inv)
            return false;
        if (inv.Expression is not MemberAccessExpressionSyntax ma)
            return false;
        if (ma.Name is not GenericNameSyntax generic)
            return false;
        if (generic.Identifier.Text != "View")
            return false;
        if (generic.TypeArgumentList.Arguments.Count != 1)
            return false;
        if (inv.ArgumentList.Arguments.Count != 1)
            return false;
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax)
            return false;
        return true;
    }

    private static Location? ExtractControlLocation(GeneratorSyntaxContext context)
    {
        var inv = (InvocationExpressionSyntax)context.Node;
        if (inv.Expression is not MemberAccessExpressionSyntax ma)
            return null;
        if (ma.Name is not GenericNameSyntax generic)
            return null;

        var typeSymbol = context.SemanticModel.GetTypeInfo(generic.TypeArgumentList.Arguments[0]).Type;
        if (typeSymbol is null)
            return null;

        var iControl = context.SemanticModel.Compilation.GetTypeByMetadataName(
            "EasyWindowsApplication.Win32ControlsModule.Frontend.IControl");
        if (iControl is null)
            return null;

        if (typeSymbol.Equals(iControl, SymbolEqualityComparer.Default))
            return inv.GetLocation();

        foreach (var iface in typeSymbol.AllInterfaces)
        {
            if (iface.Equals(iControl, SymbolEqualityComparer.Default))
                return inv.GetLocation();
        }

        return null;
    }

    private static EnclosingTypeInfo? ExtractEnclosingType(GeneratorSyntaxContext context)
    {
        var current = context.Node.Parent;
        while (current is not null)
        {
            if (current is TypeDeclarationSyntax typeDecl)
            {
                var symbol = context.SemanticModel.GetDeclaredSymbol(typeDecl);
                if (symbol is not null)
                {
                    var ns = symbol.ContainingNamespace is { IsGlobalNamespace: false } cns
                        ? cns.ToDisplayString()
                        : "";
                    return new EnclosingTypeInfo(ns, symbol.Name);
                }
            }

            if (current is CompilationUnitSyntax compilationUnit)
            {
                var hasTypeDecl = compilationUnit.Members
                    .Any(m => m is ClassDeclarationSyntax or
                              StructDeclarationSyntax or
                              RecordDeclarationSyntax);
                if (!hasTypeDecl)
                    return new EnclosingTypeInfo("", "Program");
            }

            current = current.Parent;
        }
        return null;
    }

    private static string SanitizeName(string name)
    {
        if (string.IsNullOrEmpty(name)) return "Unnamed";
        var sb = new StringBuilder();
        foreach (char c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
        }
        if (sb.Length == 0) return "Unnamed";
        if (!char.IsLetter(sb[0]) && sb[0] != '_')
            sb.Insert(0, '_');
        return sb.ToString();
    }

    private readonly struct NamedInfo(string name, string typeSymbol, bool isWindowType, Location location)
    {
        public readonly string Name = name;
        public readonly string TypeSymbol = typeSymbol;
        public readonly bool IsWindowType = isWindowType;
        public readonly Location Location = location;

        public override bool Equals(object obj) =>
            obj is NamedInfo other && Name == other.Name && TypeSymbol == other.TypeSymbol && IsWindowType == other.IsWindowType;

        public override int GetHashCode() =>
            (Name?.GetHashCode() ?? 0) ^ (TypeSymbol?.GetHashCode() ?? 0) ^ IsWindowType.GetHashCode();
    }

    private sealed class EnclosingTypeInfo(string ns, string className)
    {
        public readonly string Namespace = ns;
        public readonly string ClassName = className;
    }
}
