#nullable disable

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EasyWindowsApplication.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class EasyBehaviorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var viewCalls = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => IsViewCandidate(node),
            transform: static (ctx, _) => ExtractViewInfo(ctx))
            .Where(static info => info != null)
            .Select(static (info, _) => info!.Value);

        var collected = viewCalls.Collect();

        context.RegisterSourceOutput(collected, static (spc, controls) =>
        {
            if (controls.IsDefaultOrEmpty) return;

            var unique = new Dictionary<string, string>();
            foreach (var c in controls)
            {
                if (!unique.ContainsKey(c.Name))
                    unique[c.Name] = c.TypeSymbol;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#pragma warning disable CS0612, CS0618, CS1591");
            sb.AppendLine();

            sb.AppendLine("namespace EasyWindowsApplication");
            sb.AppendLine("{");
            sb.AppendLine("    public static class EasyBehaviorExtensions");
            sb.AppendLine("    {");

            foreach (var kv in unique)
            {
                var methodName = SanitizeName(kv.Key);
                sb.AppendLine($"        public static {kv.Value} {methodName}(this global::EasyWindowsApplication.CoreModule.Frontend.IBehaviorBuilder builder)");
                sb.AppendLine("            => builder.Get<" + kv.Value + ">(\"" + kv.Key + "\");");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("EasyBehaviorExtensions.g.cs", sb.ToString());
        });
    }

    private static bool IsViewCandidate(SyntaxNode node)
    {
        if (node is not InvocationExpressionSyntax inv)
            return false;

        if (inv.ArgumentList.Arguments.Count != 1)
            return false;

        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax)
            return false;

        if (inv.Expression is not MemberAccessExpressionSyntax memberAccess)
            return false;

        // Only match View<T>(...) — not Window(...)
        if (memberAccess.Name is GenericNameSyntax genericName
            && genericName.Identifier.Text == "View"
            && genericName.TypeArgumentList.Arguments.Count == 1)
            return true;

        return false;
    }

    private static ControlInfo? ExtractViewInfo(GeneratorSyntaxContext context)
    {
        var inv = (InvocationExpressionSyntax)context.Node;

        if (inv.Expression is not MemberAccessExpressionSyntax memberAccess)
            return null;

        if (memberAccess.Name is not GenericNameSyntax genericName
            || genericName.Identifier.Text != "View"
            || genericName.TypeArgumentList.Arguments.Count != 1)
            return null;

        var typeArg = genericName.TypeArgumentList.Arguments[0];
        var typeSymbol = context.SemanticModel.GetTypeInfo(typeArg).Type;
        if (typeSymbol == null) return null;

        var typeFullName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        if (inv.ArgumentList.Arguments[0].Expression is LambdaExpressionSyntax lambda)
        {
            var nameLiteral = FindStringArgument(lambda.Body, "Name");
            if (nameLiteral != null)
                return new ControlInfo(nameLiteral, typeFullName);
        }

        return null;
    }

    private static string FindStringArgument(SyntaxNode body, string methodName)
    {
        foreach (var inv in body.DescendantNodes().OfType<InvocationExpressionSyntax>())
        {
            if (inv.Expression is MemberAccessExpressionSyntax ma
                && ma.Name.Identifier.Text == methodName
                && inv.ArgumentList.Arguments.Count == 1
                && inv.ArgumentList.Arguments[0].Expression is LiteralExpressionSyntax literal
                && literal.IsKind(SyntaxKind.StringLiteralExpression))
            {
                return literal.Token.ValueText;
            }
        }
        return null;
    }

    private static string SanitizeName(string name)
    {
        if (string.IsNullOrEmpty(name)) return "Unnamed";
        var sb = new StringBuilder();
        foreach (char c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
        }
        if (sb.Length == 0) return "Unnamed";
        if (!char.IsLetter(sb[0]) && sb[0] != '_')
            sb.Insert(0, '_');
        return sb.ToString();
    }

    private struct ControlInfo
    {
        public readonly string Name;
        public readonly string TypeSymbol;

        public ControlInfo(string name, string typeSymbol)
        {
            Name = name;
            TypeSymbol = typeSymbol;
        }

        public override bool Equals(object obj) =>
            obj is ControlInfo other && Name == other.Name && TypeSymbol == other.TypeSymbol;

        public override int GetHashCode() => (Name?.GetHashCode() ?? 0) ^ (TypeSymbol?.GetHashCode() ?? 0);
    }
}
