<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		
		<LangVersion>latest</LangVersion>

		<IsRoslynComponent>true</IsRoslynComponent>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
		<DevelopmentDependency>true</DevelopmentDependency>

		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>EasyWindowsApplication.Generators</Title>
		<Copyright>MIT License</Copyright>
		<PackageProjectUrl>https://github.com/cl2raul66/EasyWindowsApplication/src/EasyWindowsApplication.Generators</PackageProjectUrl>
		<RepositoryUrl>https://github.com/cl2raul66/EasyWindowsApplication</RepositoryUrl>
		<PackageTags>csharp-library; win32; windows-application; easy-windows-application; Generators;</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<Version>0.0.0</Version>
		<Authors>cl2raul66</Authors>
		<Company>RandAMediaLabGroup</Company>
		<PackageId>RandAMediaLabGroup.EasyWindowsApplication.Generators</PackageId>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>logo_template.png</PackageIcon>
	</PropertyGroup>

	<ItemGroup>
		<None Include="$(TargetPath)" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
		<None Include="..\..\README.md">                 
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\rsc\Images\logo_template.png">                  
		    <Pack>True</Pack>
		    <PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="Properties\AnalyzerReleases.Shipped.md" />
		<AdditionalFiles Include="Properties\AnalyzerReleases.Unshipped.md" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="*" PrivateAssets="all"/>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="*" PrivateAssets="all" />
	</ItemGroup>

</Project>
