using Microsoft.CodeAnalysis;
using System.Text;

namespace EasyWindowsApplication.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class FilePatternsGenerator : IIncrementalGenerator
{
    private const string LibraryAssemblyName = "EasyWindowsApplication";

    // Tabla fuente: Token, Descripción, Patrones.
    // Basada en mapas de extensiones de .NET y extensiones documentadas de Windows.
    // Extensible sin cambiar la API: añadir filas emite tokens nuevos.
    private static readonly (string Token, string Description, string[] Patterns)[] Patterns =
    [
        ("PngFile", "Imagen PNG", ["*.png"]),
        ("JpgFile", "Imagen JPEG", ["*.jpg", "*.jpeg", "*.jfif"]),
        ("GifFile", "Imagen GIF", ["*.gif"]),
        ("BmpFile", "Imagen BMP", ["*.bmp"]),
        ("WebpFile", "Imagen WebP", ["*.webp"]),
        ("TiffFile", "Imagen TIFF", ["*.tiff", "*.tif"]),
        ("IcoFile", "Icono", ["*.ico"]),
        ("SvgFile", "SVG", ["*.svg"]),
        ("AllImageFile", "Imágenes", ["*.png", "*.jpg", "*.jpeg", "*.jfif", "*.gif", "*.bmp", "*.webp", "*.tiff", "*.tif", "*.ico", "*.svg"]),
        ("Mp4File", "Vídeo MP4", ["*.mp4", "*.m4v"]),
        ("MkvFile", "Vídeo MKV", ["*.mkv"]),
        ("MovFile", "Vídeo QuickTime", ["*.mov"]),
        ("AviFile", "Vídeo AVI", ["*.avi"]),
        ("WmvFile", "Vídeo WMV", ["*.wmv"]),
        ("WebmFile", "Vídeo WebM", ["*.webm"]),
        ("AllVideoFile", "Vídeos", ["*.mp4", "*.m4v", "*.mkv", "*.mov", "*.avi", "*.wmv", "*.webm", "*.mpg", "*.mpeg", "*.3gp", "*.ogv"]),
        ("Mp3File", "Audio MP3", ["*.mp3"]),
        ("WavFile", "Audio WAV", ["*.wav"]),
        ("FlacFile", "Audio FLAC", ["*.flac"]),
        ("AacFile", "Audio AAC", ["*.aac", "*.m4a"]),
        ("OggFile", "Audio Ogg", ["*.ogg", "*.oga"]),
        ("AllAudioFile", "Audio", ["*.mp3", "*.wav", "*.wma", "*.flac", "*.aac", "*.m4a", "*.ogg", "*.oga", "*.opus", "*.mid"]),
        ("PdfFile", "PDF", ["*.pdf"]),
        ("TxtFile", "Texto", ["*.txt"]),
        ("RtfFile", "RTF", ["*.rtf"]),
        ("CsvFile", "CSV", ["*.csv"]),
        ("MarkdownFile", "Markdown", ["*.md", "*.markdown"]),
        ("JsonFile", "JSON", ["*.json"]),
        ("XmlFile", "XML", ["*.xml", "*.xsl", "*.xslt"]),
        ("DocFile", "Word", ["*.doc", "*.docx"]),
        ("XlsFile", "Excel", ["*.xls", "*.xlsx", "*.xlsm"]),
        ("PptFile", "PowerPoint", ["*.ppt", "*.pptx"]),
        ("OdtFile", "OpenDocument", ["*.odt", "*.ods", "*.odp"]),
        ("EpubFile", "EPUB", ["*.epub"]),
        ("AllDocumentFile", "Documentos", ["*.pdf", "*.doc", "*.docx", "*.xls", "*.xlsx", "*.xlsm", "*.ppt", "*.pptx", "*.odt", "*.ods", "*.odp", "*.rtf", "*.txt", "*.csv", "*.epub"]),
        ("CsFile", "C#", ["*.cs"]),
        ("VbFile", "VB", ["*.vb"]),
        ("CppFile", "C/C++", ["*.c", "*.h", "*.cpp", "*.hpp", "*.cc"]),
        ("JsFile", "JavaScript", ["*.js", "*.mjs", "*.cjs"]),
        ("TsFile", "TypeScript", ["*.ts", "*.tsx"]),
        ("HtmlFile", "HTML/CSS", ["*.html", "*.htm", "*.css", "*.scss"]),
        ("PyFile", "Python", ["*.py"]),
        ("JavaFile", "Java", ["*.java"]),
        ("SqlFile", "SQL", ["*.sql"]),
        ("MdFile", "Markdown", ["*.md"]),
        ("AllCodeFile", "Código fuente", ["*.cs", "*.vb", "*.c", "*.h", "*.cpp", "*.hpp", "*.cc", "*.js", "*.mjs", "*.cjs", "*.ts", "*.tsx", "*.html", "*.htm", "*.css", "*.scss", "*.py", "*.java", "*.sql", "*.sh"]),
        ("ZipFile", "Comprimido", ["*.zip"]),
        ("RarFile", "Compresión RAR", ["*.rar"]),
        ("SevenZipFile", "7-Zip", ["*.7z"]),
        ("TarFile", "TAR", ["*.tar", "*.tar.gz", "*.tar.bz2"]),
        ("GzFile", "GZip", ["*.gz"]),
        ("AllArchiveFile", "Archivos comprimidos", ["*.zip", "*.rar", "*.7z", "*.tar", "*.gz", "*.bz2", "*.xz", "*.iso"]),
        ("ExeFile", "Ejecutables Windows", ["*.exe", "*.dll"]),
        ("BatFile", "Scripts Windows", ["*.bat", "*.cmd", "*.ps1"]),
        ("MsiFile", "MSI", ["*.msi"]),
        ("TtfFile", "Fuente TrueType", ["*.ttf"]),
        ("OtfFile", "Fuente OpenType", ["*.otf"]),
        ("WoffFile", "Fuente WOFF", ["*.woff", "*.woff2"]),
        ("ProjFile", "Solución/.NET", ["*.csproj", "*.sln", "*.fsproj", "*.vbproj", "*.props", "*.targets"]),
        ("NupkgFile", "Paquete NuGet", ["*.nupkg"]),
        ("AllFile", "Todos los archivos", ["*.*"]),
    ];

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.CompilationProvider.Select(static (compilation, _) =>
                compilation.AssemblyName == LibraryAssemblyName),
            static (spc, isLibrary) =>
            {
                if (isLibrary)
                {
                    var sb = new StringBuilder();
                    sb.AppendLine("// <auto-generated />");
                    sb.AppendLine();
                    sb.AppendLine("namespace EasyWindowsApplication.Share;");
                    sb.AppendLine();
                    sb.AppendLine("public static class FilePatterns");
                    sb.AppendLine("{");
                    foreach (var (token, description, patterns) in Patterns)
                    {
                        var array = string.Join(", ", System.Linq.Enumerable.Select(patterns, p => $"\"{p}\""));
                        sb.AppendLine($"    public static readonly FilePattern {token} = new(\"{Escape(description)}\", new[] {{ {array} }});");
                    }
                    sb.AppendLine("}");
                    spc.AddSource("FilePatterns.g.cs", sb.ToString());
                }

                spc.AddSource("FilePatternsUsings.g.cs",
                    "// <auto-generated />\nglobal using static EasyWindowsApplication.Share.FilePatterns;\n");
            });
    }

    private static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
